default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "db" } %>
  username: <%= ENV.fetch("DATABASE_USER") { "postgres" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "password" } %>

development:
  <<: *default
  database: vendezvotremontre_development

test:
  <<: *default
  database: vendezvotremontre_test

production:
  <<: *default
  database: vendezvotremontre_production
  username: <%= ENV.fetch("VENDEZVOTREMONTRE_DATABASE_USER") { "vendezvotremontre" } %>
  password: <%= ENV.fetch("VENDEZVOTREMONTRE_DATABASE_PASSWORD") { "password" } %>
